# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 05:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditionName', models.CharField(max_length=50)),
                ('subCondition', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('writtenBy', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=75, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=75, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phoneNumber', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+16045555555'.", regex='^\\+?1?\\d{10,12}$')], verbose_name='Number')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('province', models.CharField(blank=True, choices=[('QC', 'Quebec'), ('NU', 'Nunavut'), ('NS', 'Nova Scotia'), ('NL', 'Newfoundland and Labrador'), ('YT', 'Yukon'), ('SK', 'Saskatchewan'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('NB', 'New Brunswick'), ('NT', 'Northwest Territories'), ('MB', 'Manitoba'), ('AB', 'Alberta'), ('BC', 'British Columbia')], max_length=20, null=True, verbose_name='Province')),
                ('postalCode', models.CharField(blank=True, max_length=6, null=True, verbose_name='Postal Code')),
                ('numberOfUpvotes', models.IntegerField(blank=True, max_length=75, null=True, verbose_name='Number of Upvotes')),
                ('userSince', models.DateField(blank=True, default='', max_length=75, null=True, verbose_name='User Since')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('transcript', models.CharField(max_length=1000000)),
                ('author', models.CharField(max_length=60)),
                ('publication_date', models.DateField()),
                ('condition', models.CharField(choices=[('ASD', 'Autism Spectrum Disorders'), ('AD', 'Attachment Disorders'), ('ADHD', 'Attention Deficit/Hyperactivity Disorder'), ('A', 'Autism'), ('CD', 'Conduct Disorder'), ('DoWE', 'Disorder of Written Expression'), ('DMDD', 'Disruptive Mood Dysregulation Disorder'), ('Enc', 'Encopresis'), ('Enu', 'Enuresis'), ('ELD', 'Expressive Language Disorder'), ('MD', 'Mathematics Disorder'), ('ID', 'Intellectual Disability'), ('OCD', 'Obsessive-Compulsive Disorder'), ('ODD', 'Oppositional Defiant Disorder'), ('ReD', 'Reading Disorder'), ('RuD', 'Rumination Disorder'), ('SM', 'Selective Mutism'), ('SAD', 'Separation Anxiety Disorder'), ('SCD', 'Social Communication Disorder'), ('SMD', 'Stereotypic Movement Disorder'), ('S', 'Stuttering'), ('TD', "Tourette's Disorder"), ('TTD', 'Transient Tic Disorder')], max_length=4)),
            ],
        ),
    ]
