# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hestia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='province',
            field=models.CharField(blank=True, choices=[('QC', 'Quebec'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('BC', 'British Columbia'), ('YT', 'Yukon'), ('AB', 'Alberta'), ('MB', 'Manitoba'), ('NU', 'Nunavut'), ('SK', 'Saskatchewan'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NB', 'New Brunswick'), ('NT', 'Northwest Territories')], max_length=20, null=True, verbose_name='Province'),
        ),
    ]
