# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 06:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hestia', '0003_auto_20170930_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=75, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=75, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phoneNumber', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+16045555555'.", regex='^\\+?1?\\d{10,12}$')], verbose_name='Number')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('province', models.CharField(blank=True, choices=[('NS', 'Nova Scotia'), ('MB', 'Manitoba'), ('ON', 'Ontario'), ('NU', 'Nunavut'), ('SK', 'Saskatchewan'), ('YT', 'Yukon'), ('NT', 'Northwest Territories'), ('BC', 'British Columbia'), ('AB', 'Alberta'), ('QC', 'Quebec'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('PE', 'Prince Edward Island')], max_length=20, null=True, verbose_name='Province')),
                ('postalCode', models.CharField(blank=True, max_length=6, null=True, verbose_name='Postal Code')),
                ('numberOfUpvotes', models.IntegerField(blank=True, null=True, verbose_name='Number of Upvotes')),
                ('userSince', models.DateField(blank=True, default='', max_length=75, null=True, verbose_name='User Since')),
            ],
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.AlterField(
            model_name='question',
            name='upvotes',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Hestia.User'),
        ),
    ]
