# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hestia', '0004_auto_20170930_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, choices=[('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('MB', 'Manitoba'), ('ON', 'Ontario'), ('SK', 'Saskatchewan'), ('AB', 'Alberta'), ('YT', 'Yukon'), ('BC', 'British Columbia'), ('PE', 'Prince Edward Island'), ('NL', 'Newfoundland and Labrador'), ('NB', 'New Brunswick'), ('NT', 'Northwest Territories'), ('QC', 'Quebec')], max_length=20, null=True, verbose_name='Province'),
        ),
    ]
