# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 09:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hestia', '0005_auto_20170930_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('upvotes', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, choices=[('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('YT', 'Yukon'), ('NT', 'Northwest Territories'), ('NS', 'Nova Scotia'), ('QC', 'Quebec'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('AB', 'Alberta'), ('NL', 'Newfoundland and Labrador'), ('SK', 'Saskatchewan'), ('NU', 'Nunavut')], max_length=20, null=True, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Hestia.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Hestia.Question'),
        ),
    ]
